apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-machine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-machine
  template:
    metadata:
      labels:
        app: time-machine
    spec:
      containers:
      - name: auth
        image: gcr.io/cs144-25s-team34/tm-auth:latest
        envFrom:
        - secretRef:
            name: time-machine-env
        ports:
        - containerPort: 3000
      - name: forecast
        image: gcr.io/cs144-25s-team34/tm-forecast:latest
        envFrom:
        - secretRef:
            name: time-machine-env
        ports:
        - containerPort: 8000
      - name: frontend
        image: gcr.io/cs144-25s-team34/tm-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: time-machine
spec:
  type: LoadBalancer
  selector:
    app: time-machine
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 80
      name: https