apiVersion: v1
kind: Secret
metadata:
  name: time-machine-env
type: Opaque
stringData:
  # Copy values from your .env file here. Do NOT commit secrets to git.
  MONGO_URI: ""
  JWT_SECRET: ""
  NODE_ENV: "production"
  # Add other env vars (API_KEY, etc.) used by forecast_module here
  # API_KEY: ""
